/**
 * Optimizes site images: cohort carousel, intern headshots, apply section.
 * Sources cohort originals from ../Photos when available; otherwise re-processes public/photos.
 *
 * Run: npm run photos
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import {
  buildSrcSet,
  generateWebpVariants,
  isSourceImage,
  listImageFiles,
  removeLegacyImages,
  removeStaleWebp,
  slugFromFilename,
} from './lib/image-optimize.mjs'

const root = path.join(fileURLToPath(import.meta.url), '..', '..')
const photosSource = path.join(root, '..', 'Photos')
const photosPublic = path.join(root, 'public', 'photos')
const internsPublic = path.join(root, 'public', 'interns')
const eventsPublic = path.join(root, 'public', 'events')
const cohortManifest = path.join(root, 'src', 'data', 'cohortPhotos.generated.js')
const internManifest = path.join(root, 'src', 'data', 'internPhotos.generated.js')
const staticManifest = path.join(root, 'src', 'data', 'staticImages.generated.js')

const COHORT_WIDTHS = [280, 560]
const INTERN_WIDTHS = [400, 800]
const APPLY_WIDTHS = [600, 900, 1200]
const IVORY_CENTER_WIDTHS = [480, 720, 1024]
const EVENT_WIDTHS = [400, 696, 1200]

const COHORT_SIZES = '(max-width: 640px) 180px, (max-width: 768px) 220px, 280px'
const INTERN_SIZES = '(max-width: 640px) 45vw, (max-width: 1024px) 22vw, 260px'
const INTERN_MODAL_SIZES = '(max-width: 520px) 100vw, 520px'
const APPLY_SIZES = '(max-width: 768px) 100vw, 50vw'
const IVORY_CENTER_SIZES = '(min-width: 768px) 520px, 100vw'
const EVENT_SIZES = '(min-width: 768px) 33vw, 100vw'

const PAST_EVENT_ORDER = [
  'build-with-ai-workshop',
  'code-to-success-morning',
  'social-media-101-workshop',
  'umbp-interns-2017',
  'commencement-dinner',
  'on-the-ground-moldova',
]

function altFromFilename(filename) {
  const IMAGE_RE = /\.(jpe?g|png|webp|gif|avif)$/i
  const base = filename.replace(IMAGE_RE, '')
  if (/^DSCF\d+/i.test(base) || /^[A-F0-9-]{20,}/i.test(base)) {
    return 'UMBP intern cohort'
  }
  const label = base.replace(/[_-]+/g, ' ').trim()
  return label ? `UMBP cohort — ${label}` : 'UMBP intern cohort'
}

function writeJsModule(filePath, exportName, value) {
  const source = `// Auto-generated by "npm run photos" — do not edit

export const ${exportName} = ${JSON.stringify(value, null, 2)}
`
  fs.writeFileSync(filePath, source)
}

function readExistingManifest(filePath, exportName) {
  if (!fs.existsSync(filePath)) return null
  const text = fs.readFileSync(filePath, 'utf8')
  const match = text.match(new RegExp(`export const ${exportName} = ([\\s\\S]+)$`))
  if (!match) return null
  try {
    return JSON.parse(match[1])
  } catch {
    return null
  }
}

function rebuildCohortManifestFromWebp() {
  const bySlug = new Map()

  for (const file of fs.readdirSync(photosPublic)) {
    const match = file.match(/^(.+)-(\d+)w\.webp$/)
    if (!match) continue
    const [, slug, width] = match
    if (!bySlug.has(slug)) bySlug.set(slug, [])
    bySlug.get(slug).push({ width: Number(width), file })
  }

  return [...bySlug.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([slug, entries]) => {
      entries.sort((a, b) => a.width - b.width)
      const primary = entries[entries.length - 1]
      const prefix = '/photos'
      return {
        src: `${prefix}/${primary.file}`,
        srcSet: buildSrcSet(entries, prefix),
        sizes: COHORT_SIZES,
        width: primary.width,
        height: primary.width,
        alt: altFromFilename(`${slug}.jpg`),
      }
    })
}

function rebuildInternManifestFromWebp() {
  const assets = {}

  for (const file of fs.readdirSync(internsPublic)) {
    const match = file.match(/^(.+)-(\d+)w\.webp$/)
    if (!match) continue
    const [, id, width] = match
    if (!assets[id]) assets[id] = []
    assets[id].push({ width: Number(width), file })
  }

  const result = {}
  for (const [id, entries] of Object.entries(assets)) {
    entries.sort((a, b) => a.width - b.width)
    const primary = entries[entries.length - 1]
    const prefix = '/interns'
    result[id] = {
      src: `${prefix}/${primary.file}`,
      srcSet: buildSrcSet(entries, prefix),
      sizes: INTERN_SIZES,
      modalSizes: INTERN_MODAL_SIZES,
      width: primary.width,
      height: primary.width,
    }
  }
  return result
}

function rebuildApplyManifestFromWebp() {
  const outputDir = path.join(root, 'public')
  const entries = []

  for (const file of fs.readdirSync(outputDir)) {
    const match = file.match(/^apply-summer-program-(\d+)w\.webp$/)
    if (!match) continue
    entries.push({ width: Number(match[1]), file })
  }

  if (!entries.length) return null

  entries.sort((a, b) => a.width - b.width)
  const primary = entries[entries.length - 1]
  return {
    src: `/${primary.file}`,
    srcSet: buildSrcSet(entries, ''),
    sizes: APPLY_SIZES,
    width: primary.width,
    height: primary.height,
  }
}

function rebuildIvoryCenterManifestFromWebp() {
  const outputDir = path.join(root, 'public')
  const entries = []

  for (const file of fs.readdirSync(outputDir)) {
    const match = file.match(/^ivory-center-(\d+)w\.webp$/)
    if (!match) continue
    entries.push({ width: Number(match[1]), file })
  }

  if (!entries.length) return null

  entries.sort((a, b) => a.width - b.width)
  const primary = entries[entries.length - 1]
  return {
    src: `/${primary.file}`,
    srcSet: buildSrcSet(entries, ''),
    sizes: IVORY_CENTER_SIZES,
    width: primary.width,
    height: primary.height,
  }
}

function rebuildPastEventPhotosFromWebp() {
  if (!fs.existsSync(eventsPublic)) return []

  const bySlug = new Map()

  for (const file of fs.readdirSync(eventsPublic)) {
    const match = file.match(/^(.+)-(\d+)w\.webp$/)
    if (!match) continue
    const [, slug, width] = match
    if (!bySlug.has(slug)) bySlug.set(slug, [])
    bySlug.get(slug).push({ width: Number(width), file })
  }

  const prefix = '/events'
  return PAST_EVENT_ORDER.filter((slug) => bySlug.has(slug)).map((slug) => {
    const entries = bySlug.get(slug).sort((a, b) => a.width - b.width)
    const primary = entries[entries.length - 1]
    return {
      id: slug,
      src: `${prefix}/${primary.file}`,
      srcSet: buildSrcSet(entries, prefix),
      sizes: EVENT_SIZES,
      width: primary.width,
      height: primary.height,
    }
  })
}

function writeStaticImagesManifest(applySummerProgramImage, ivoryCenterImage, pastEventPhotos) {
  const source = `// Auto-generated by "npm run photos" — do not edit

export const applySummerProgramImage = ${JSON.stringify(applySummerProgramImage, null, 2)}

export const ivoryCenterImage = ${JSON.stringify(ivoryCenterImage, null, 2)}

export const pastEventPhotos = ${JSON.stringify(pastEventPhotos, null, 2)}
`
  fs.writeFileSync(staticManifest, source)
}

async function optimizeCohortPhotos() {
  const sourceFiles = listImageFiles(photosSource)
  let inputs = []

  if (sourceFiles.length > 0) {
    inputs = sourceFiles.map((file) => ({
      file,
      inputPath: path.join(photosSource, file),
      slug: slugFromFilename(file),
      alt: altFromFilename(file),
    }))
  } else {
    const existing = listImageFiles(photosPublic).filter(isSourceImage)
    if (existing.length === 0) {
      const rebuilt = rebuildCohortManifestFromWebp()
      if (rebuilt.length) {
        writeJsModule(cohortManifest, 'internCohortPhotos', rebuilt)
        console.warn(`Rebuilt cohort manifest from ${rebuilt.length} existing WebP file(s)`)
        return rebuilt.length
      }
      console.warn('No cohort photos in ../Photos or public/photos/')
      const prior = readExistingManifest(cohortManifest, 'internCohortPhotos')
      if (prior?.length) return prior.length
      writeJsModule(cohortManifest, 'internCohortPhotos', [])
      return 0
    }
    console.warn(
      `../Photos not available — re-optimizing ${existing.length} file(s) in public/photos`,
    )
    inputs = existing.map((file) => ({
      file,
      inputPath: path.join(photosPublic, file),
      slug: slugFromFilename(file),
      alt: altFromFilename(file),
    }))
  }

  fs.mkdirSync(photosPublic, { recursive: true })
  const validSlugs = new Set()
  const manifest = []

  for (const { inputPath, slug, alt } of inputs) {
    validSlugs.add(slug)
    const { entries, primary } = await generateWebpVariants(
      inputPath,
      photosPublic,
      slug,
      COHORT_WIDTHS,
      { quality: 80, square: true },
    )

    const prefix = '/photos'
    manifest.push({
      src: `${prefix}/${primary.file}`,
      srcSet: buildSrcSet(entries, prefix),
      sizes: COHORT_SIZES,
      width: primary.width,
      height: primary.height,
      alt,
    })
  }

  removeStaleWebp(photosPublic, validSlugs)
  removeLegacyImages(photosPublic)

  writeJsModule(cohortManifest, 'internCohortPhotos', manifest)
  return manifest.length
}

async function optimizeInternPhotos() {
  const sourceFiles = listImageFiles(internsPublic).filter(isSourceImage)

  if (sourceFiles.length === 0) {
    const rebuilt = rebuildInternManifestFromWebp()
    const count = Object.keys(rebuilt).length
    if (count) {
      writeJsModule(internManifest, 'internPhotoAssets', rebuilt)
      console.warn(`Rebuilt intern manifest from ${count} existing WebP file(s)`)
      return count
    }
    const prior = readExistingManifest(internManifest, 'internPhotoAssets')
    if (prior && Object.keys(prior).length) {
      return Object.keys(prior).length
    }
    writeJsModule(internManifest, 'internPhotoAssets', {})
    return 0
  }

  const assets = {}
  const validSlugs = new Set()

  for (const file of sourceFiles) {
    const id = file.replace(/\.(jpe?g|png|gif|avif|webp)$/i, '').toLowerCase()
    validSlugs.add(id)

    const inputPath = path.join(internsPublic, file)
    const { entries, primary } = await generateWebpVariants(
      inputPath,
      internsPublic,
      id,
      INTERN_WIDTHS,
      { quality: 82, square: true },
    )

    const prefix = '/interns'
    assets[id] = {
      src: `${prefix}/${primary.file}`,
      srcSet: buildSrcSet(entries, prefix),
      sizes: INTERN_SIZES,
      modalSizes: INTERN_MODAL_SIZES,
      width: primary.width,
      height: primary.height,
    }
  }

  removeStaleWebp(internsPublic, validSlugs)
  removeLegacyImages(internsPublic)

  writeJsModule(internManifest, 'internPhotoAssets', assets)
  return Object.keys(assets).length
}

async function optimizeApplyImage() {
  const outputDir = path.join(root, 'public')
  const inputPath = ['png', 'jpg', 'jpeg']
    .map((ext) => path.join(outputDir, `apply-summer-program.${ext}`))
    .find((candidate) => fs.existsSync(candidate))

  if (!inputPath) {
    const rebuilt = rebuildApplyManifestFromWebp()
    if (rebuilt) return rebuilt
    const prior = readExistingManifest(staticManifest, 'applySummerProgramImage')
    if (prior) return prior
    console.warn('apply-summer-program source not found — skipping')
    return null
  }

  for (const file of fs.readdirSync(outputDir)) {
    if (file.startsWith('apply-summer-program-') && file.endsWith('.webp')) {
      fs.unlinkSync(path.join(outputDir, file))
    }
  }

  const { entries, primary } = await generateWebpVariants(
    inputPath,
    outputDir,
    'apply-summer-program',
    APPLY_WIDTHS,
    { quality: 85, maxWidth: 1200 },
  )

  return {
    src: `/${primary.file}`,
    srcSet: buildSrcSet(entries, ''),
    sizes: APPLY_SIZES,
    width: primary.width,
    height: primary.height,
  }
}

async function optimizeIvoryCenterImage() {
  const outputDir = path.join(root, 'public')
  const inputPath = ['png', 'jpg', 'jpeg']
    .map((ext) => path.join(outputDir, `ivory-center.${ext}`))
    .find((candidate) => fs.existsSync(candidate))

  if (!inputPath) {
    const rebuilt = rebuildIvoryCenterManifestFromWebp()
    if (rebuilt) return rebuilt
    const prior = readExistingManifest(staticManifest, 'ivoryCenterImage')
    if (prior) return prior
    console.warn('ivory-center source not found — skipping')
    return null
  }

  for (const file of fs.readdirSync(outputDir)) {
    if (file.startsWith('ivory-center-') && file.endsWith('.webp')) {
      fs.unlinkSync(path.join(outputDir, file))
    }
  }

  const { entries, primary } = await generateWebpVariants(
    inputPath,
    outputDir,
    'ivory-center',
    IVORY_CENTER_WIDTHS,
    { quality: 85, maxWidth: 1024 },
  )

  return {
    src: `/${primary.file}`,
    srcSet: buildSrcSet(entries, ''),
    sizes: IVORY_CENTER_SIZES,
    width: primary.width,
    height: primary.height,
  }
}

async function optimizePastEventPhotos() {
  if (!fs.existsSync(eventsPublic)) {
    const rebuilt = rebuildPastEventPhotosFromWebp()
    if (rebuilt.length) return rebuilt
    const prior = readExistingManifest(staticManifest, 'pastEventPhotos')
    if (prior?.length) return prior
    return []
  }

  const sourceFiles = listImageFiles(eventsPublic).filter(isSourceImage)
  if (sourceFiles.length === 0) {
    const rebuilt = rebuildPastEventPhotosFromWebp()
    if (rebuilt.length) return rebuilt
    const prior = readExistingManifest(staticManifest, 'pastEventPhotos')
    if (prior?.length) return prior
    return []
  }

  const validSlugs = new Set(PAST_EVENT_ORDER)

  for (const file of sourceFiles) {
    const id = file.replace(/\.(jpe?g|png|gif|avif|webp)$/i, '').toLowerCase()
    validSlugs.add(id)

    const inputPath = path.join(eventsPublic, file)
    await generateWebpVariants(
      inputPath,
      eventsPublic,
      id,
      EVENT_WIDTHS,
      { quality: 85, maxWidth: 1200 },
    )
  }

  removeStaleWebp(eventsPublic, validSlugs)
  removeLegacyImages(eventsPublic)

  return rebuildPastEventPhotosFromWebp()
}

const cohortCount = await optimizeCohortPhotos()
const internCount = await optimizeInternPhotos()
const applyImage = await optimizeApplyImage()
const ivoryCenterImage = await optimizeIvoryCenterImage()
const pastEventPhotos = await optimizePastEventPhotos()
writeStaticImagesManifest(applyImage, ivoryCenterImage, pastEventPhotos)

console.log(
  `Optimized ${cohortCount} cohort photo(s), ${internCount} intern headshot(s), apply image, ivory center image, ${pastEventPhotos.length} past event photo(s).`,
)
